### ISSUE TITLE
how ignore __test__ folder.

### ISSUE THREAD

**Issue by neozhu** [forcedotcom/run-code-analyzer#25]
Could you please take a look at it.

also I add  to .eslintignore
```
**/aura/**/__test__/**
**/lwc/**/__test__/**
```

![image](https://github.com/forcedotcom/run-code-analyzer/assets/1549611/b150a1ab-07bc-4b42-8089-d3224a871875)

```yml
- name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --engine "eslint-lwc,pmd" --normalize-severity --target "force-app/main/**/*.cls,force-app/main/**/*.js,!force-app/main/**/__test__/**" --outfile salesforce-code-analyzer-results.html --pmdconfig ".github/workflows/pmd-ruleset.xml"
          results-artifact-name: salesforce-code-analyzer-results
  ```
 not working for parameters --target "force-app/main/**/*.cls,force-app/main/**/*.js,!force-app/main/**/__test__/**"
 
 has other solution.
